version: '3.9'

services:
  valley:
    build:
      context: ./docker
      cache_from:
        - type=local,src=../Image Cache
      cache_to:
        - type=local,dest=../Image Cache
    image: samkintop/stardew-valley-docker-image:latest
    shm_size: '2g'
    container_name: stardew
    deploy:
      resources:
        limits:
          cpus: '7.5'
          memory: 12G
        reservations:
          cpus: '4'
          memory: 4G
    ports:
      # VNC
      - 5902:5900
      # NOVNC WEB
      - 5801:5800
      # Game
      - 24642:24642/udp
    volumes:
      # Saves go here now
      - ./valley_saves:/config/xdg/config/StardewValley/Saves
      # TigerVNC Security Keys
      - ./TigerVNC/Security:/etc/tigervnc/security
      - ./TigerVNC/Config:/etc/tigervnc/config
    environment:
      - VNC_PASSWORD=stardew
      - DISPLAY_HEIGHT=900
      - DISPLAY_WIDTH=1200
      - SECURITY_TYPES=X509Vnc,TLSVnc
      - X509_CERT_FILE=/etc/tigervnc/security/cert.pem
      - X509_KEY_FILE=/etc/tigervnc/security/key.pem
      - PROTOCOL=3.8
      - JPEG_QUALITY=70
      - JPEG_COMPRESSION=6
      ## Always On Server mod
      # Removing this will probably defeat the point of ever using this?
      - ENABLE_ALWAYSONSERVER_MOD=${ENABLE_ALWAYSONSERVER_MOD-true}
      - ALWAYS_ON_SERVER_HOTKEY=${ALWAYS_ON_SERVER_HOTKEY-F9}
      - ALWAYS_ON_SERVER_PROFIT_MARGIN=${ALWAYS_ON_SERVER_PROFIT_MARGIN-100}
      - ALWAYS_ON_SERVER_UPGRADE_HOUSE=${ALWAYS_ON_SERVER_UPGRADE_HOUSE-0}
      - ALWAYS_ON_SERVER_PET_NAME=${ALWAYS_ON_SERVER_PET_NAME-Ketchup}
      - ALWAYS_ON_SERVER_FARM_CAVE_CHOICE_MUSHROOMS=${ALWAYS_ON_SERVER_FARM_CAVE_CHOICE_MUSHROOMS-false}
      - ALWAYS_ON_SERVER_COMMUNITY_CENTER_RUN=${ALWAYS_ON_SERVER_COMMUNITY_CENTER_RUN-true}
      - ALWAYS_ON_SERVER_TIME_OF_DAY_TO_SLEEP=${ALWAYS_ON_SERVER_TIME_OF_DAY_TO_SLEEP-2200}
      - ALWAYS_ON_SERVER_LOCK_PLAYER_CHESTS=${ALWAYS_ON_SERVER_LOCK_PLAYER_CHESTS-false}
      - ALWAYS_ON_SERVER_CLIENTS_CAN_PAUSE=${ALWAYS_ON_SERVER_CLIENTS_CAN_PAUSE-true}
      - ALWAYS_ON_SERVER_COPY_INVITE_CODE_TO_CLIPBOARD=${ALWAYS_ON_SERVER_COPY_INVITE_CODE_TO_CLIPBOARD-false}

      - ALWAYS_ON_SERVER_FESTIVALS_ON=${ALWAYS_ON_SERVER_FESTIVALS_ON-true}
      - ALWAYS_ON_SERVER_EGG_HUNT_COUNT_DOWN=${ALWAYS_ON_SERVER_EGG_HUNT_COUNT_DOWN-600}
      - ALWAYS_ON_SERVER_FLOWER_DANCE_COUNT_DOWN=${ALWAYS_ON_SERVER_FLOWER_DANCE_COUNT_DOWN-600}
      - ALWAYS_ON_SERVER_LUAU_SOUP_COUNT_DOWN=${ALWAYS_ON_SERVER_LUAU_SOUP_COUNT_DOWN-600}
      - ALWAYS_ON_SERVER_JELLY_DANCE_COUNT_DOWN=${ALWAYS_ON_SERVER_JELLY_DANCE_COUNT_DOWN-600}
      - ALWAYS_ON_SERVER_GRANGE_DISPLAY_COUNT_DOWN=${ALWAYS_ON_SERVER_GRANGE_DISPLAY_COUNT_DOWN-600}
      - ALWAYS_ON_SERVER_ICE_FISHING_COUNT_DOWN=${ALWAYS_ON_SERVER_ICE_FISHING_COUNT_DOWN-600}

      - ALWAYS_ON_SERVER_END_OF_DAY_TIMEOUT=${ALWAYS_ON_SERVER_END_OF_DAY_TIMEOUT-300}
      - ALWAYS_ON_SERVER_FAIR_TIMEOUT=${ALWAYS_ON_SERVER_FAIR_TIMEOUT-1200}
      - ALWAYS_ON_SERVER_SPIRITS_EVE_TIMEOUT=${ALWAYS_ON_SERVER_SPIRITS_EVE_TIMEOUT-900}
      - ALWAYS_ON_SERVER_WINTER_STAR_TIMEOUT=${ALWAYS_ON_SERVER_WINTER_STAR_TIMEOUT-900}

      - ALWAYS_ON_SERVER_EGG_FESTIVAL_TIMEOUT=${ALWAYS_ON_SERVER_EGG_FESTIVAL_TIMEOUT-120}
      - ALWAYS_ON_SERVER_FLOWER_DANCE_TIMEOUT=${ALWAYS_ON_SERVER_FLOWER_DANCE_TIMEOUT-120}
      - ALWAYS_ON_SERVER_LUAU_TIMEOUT=${ALWAYS_ON_SERVER_LUAU_TIMEOUT-120}
      - ALWAYS_ON_SERVER_DANCE_OF_JELLIES_TIMEOUT=${ALWAYS_ON_SERVER_DANCE_OF_JELLIES_TIMEOUT-120}
      - ALWAYS_ON_SERVER_FESTIVAL_OF_ICE_TIMEOUT=${ALWAYS_ON_SERVER_FESTIVAL_OF_ICE_TIMEOUT-120 }
      ## Unlimited Players mod
      # Removing this will limit game players to 4
      - ENABLE_UNLIMITEDPLAYERS_MOD=${ENABLE_UNLIMITEDPLAYERS_MOD-false}
      - UNLIMITED_PLAYERS_PLAYER_LIMIT=${UNLIMITED_PLAYERS_PLAYER_LIMIT-10}
      
      ## Remote Control mod
      # Disabling this will remove the ability to automatically sleep and save on shutdown
      - ENABLE_REMOTECONTROL_MOD=${ENABLE_REMOTECONTROL_MOD-true}
      - REMOTE_CONTROL_EVERYONE_IS_ADMIN=${REMOTE_CONTROL_EVERYONE_IS_ADMIN-true}    # Disable any authorization by just making everyone an admin - useful for private servers where everyone is trusted
      - REMOTE_CONTROL_DEFAULT_ADMINS=${REMOTE_CONTROL_DEFAULT_ADMINS-}   # A list of comma-separated json objects to use as default admins, eg: {id: "123456789", name: "Seb"}, {id: "987654321", name: "Kitz"}
      - REMOTE_CONTROL_SHOULD_ASSIGN_ADMIN_TO_FIRST_CABIN_FARMER=${REMOTE_CONTROL_SHOULD_ASSIGN_ADMIN_TO_FIRST_CABIN_FARMER-true}   # Give the first player that connects admin privileges

      ## Save Backup mod
      # Disabling this will stop saves being backed up
      - ENABLE_SAVEBACKUP_MOD=${ENABLE_SAVEBACKUP_MOD-true}

      ## Chat Commands mod
      - ENABLE_CHATCOMMANDS_MOD=${ENABLE_CHATCOMMANDS_MOD-true}

      ## Console Commands mod
      - ENABLE_CONSOLECOMMANDS_MOD=${ENABLE_CONSOLECOMMANDS_MOD-true}

      ## Time Speed mod
      - ENABLE_TIMESPEED_MOD=${ENABLE_TIMESPEED_MOD-true}

      # Days are only 20 hours long
      #   7.0 = 14 mins per in game day (default)
      #  10.0 = 20 mins
      #  15.0 = 30 mins
      #  20.0 = 40 mins
      #  30.0 = 1 hour
      # 120.0 = 4 hours
      # 300.0 = 10 hours
      # 600.0 = 20 hours (realtime)

      - TIME_SPEED_DEFAULT_TICK_LENGTH=${TIME_SPEED_DEFAULT_TICK_LENGTH-15.0}
      - TIME_SPEED_TICK_LENGTH_BY_LOCATION_INDOORS=${TIME_SPEED_TICK_LENGTH_BY_LOCATION_INDOORS-15.0}
      - TIME_SPEED_TICK_LENGTH_BY_LOCATION_OUTDOORS=${TIME_SPEED_TICK_LENGTH_BY_LOCATION_OUTDOORS-15.0}
      - TIME_SPEED_TICK_LENGTH_BY_LOCATION_MINE=${TIME_SPEED_TICK_LENGTH_BY_LOCATION_MINE-15.0}

      - TIME_SPEED_ENABLE_ON_FESTIVAL_DAYS=${TIME_SPEED_ENABLE_ON_FESTIVAL_DAYS-true}
      - TIME_SPEED_FREEZE_TIME_AT=${TIME_SPEED_FREEZE_TIME_AT-null}
      - TIME_SPEED_LOCATION_NOTIFY=${TIME_SPEED_LOCATION_NOTIFY-false}

      - TIME_SPEED_KEYS_FREEZE_TIME=${TIME_SPEED_KEYS_FREEZE_TIME-N}
      - TIME_SPEED_KEYS_INCREASE_TICK_INTERVAL=${TIME_SPEED_KEYS_INCREASE_TICK_INTERVAL-OemPeriod}
      - TIME_SPEED_KEYS_DECREASE_TICK_INTERVAL=${TIME_SPEED_KEYS_DECREASE_TICK_INTERVAL-OemComma}
      - TIME_SPEED_KEYS_RELOAD_CONFIG=${TIME_SPEED_KEYS_RELOAD_CONFIG-B}

      ## Crops Anytime Anywhere mod
      - ENABLE_CROPSANYTIMEANYWHERE_MOD=${ENABLE_CROPSANYTIMEANYWHERE_MOD-false}

      - CROPS_ANYTIME_ANYWHERE_ENABLE_IN_SEASONS_SPRING=${CROPS_ANYTIME_ANYWHERE_ENABLE_IN_SEASONS_SPRING-true}
      - CROPS_ANYTIME_ANYWHERE_ENABLE_IN_SEASONS_SUMMER=${CROPS_ANYTIME_ANYWHERE_ENABLE_IN_SEASONS_SUMMER-true}
      - CROPS_ANYTIME_ANYWHERE_ENABLE_IN_SEASONS_FALL=${CROPS_ANYTIME_ANYWHERE_ENABLE_IN_SEASONS_FALL-true}
      - CROPS_ANYTIME_ANYWHERE_ENABLE_IN_SEASONS_WINTER=${CROPS_ANYTIME_ANYWHERE_ENABLE_IN_SEASONS_WINTER-true}

      - CROPS_ANYTIME_ANYWHERE_FARM_ANY_LOCATION=${CROPS_ANYTIME_ANYWHERE_FARM_ANY_LOCATION-true}

      - CROPS_ANYTIME_ANYWHERE_FORCE_TILLABLE_DIRT=${CROPS_ANYTIME_ANYWHERE_FORCE_TILLABLE_DIRT-true}
      - CROPS_ANYTIME_ANYWHERE_FORCE_TILLABLE_GRASS=${CROPS_ANYTIME_ANYWHERE_FORCE_TILLABLE_GRASS-true}
      - CROPS_ANYTIME_ANYWHERE_FORCE_TILLABLE_STONE=${CROPS_ANYTIME_ANYWHERE_FORCE_TILLABLE_STONE-false}
      - CROPS_ANYTIME_ANYWHERE_FORCE_TILLABLE_OTHER=${CROPS_ANYTIME_ANYWHERE_FORCE_TILLABLE_OTHER-false}

      ## Friends Forever mod
      - ENABLE_FRIENDSFOREVER_MOD=${ENABLE_FRIENDSFOREVER_MOD-false}

      - FRIENDS_FOREVER_AFFECT_SPOUSE=${FRIENDS_FOREVER_AFFECT_SPOUSE-false}
      - FRIENDS_FOREVER_AFFECT_DATES=${FRIENDS_FOREVER_AFFECT_DATES-true}
      - FRIENDS_FOREVER_AFFECT_EVERYONE_ELSE=${FRIENDS_FOREVER_AFFECT_EVERYONE_ELSE-true}
      - FRIENDS_FOREVER_AFFECT_ANIMALS=${FRIENDS_FOREVER_AFFECT_ANIMALS-true}

      ## No Fence Decay mod
      - ENABLE_NOFENCEDECAY_MOD=${ENABLE_NOFENCEDECAY_MOD-false}

      ## Non-destructive NPCs mod
      - ENABLE_NONDESTRUCTIVENPCS_MOD=${ENABLE_NONDESTRUCTIVENPCS_MOD-true}

      - ENABLE_CONTENTPATCHER_MOD=${ENABLE_CONTENTPATCHER_MOD-true}
      - ENABLE_CUSTOMNPCEXCLUSIONS_MOD=${ENABLE_CUSTOMNPCEXCLUSIONS_MOD-true}
      - ENABLE_EXPANDEDPRECONDITIONSUTILITY_MOD=${ENABLE_EXPANDEDPRECONDITIONSUTILITY_MOD-true}
      - ENABLE_EXTRAMAPLAYERS_MOD=${ENABLE_EXTRAMAPLAYERS_MOD-true}
      - ENABLE_FARMTYPEMANAGER_MOD=${ENABLE_FARMTYPEMANAGER_MOD-true}
      - ENABLE_GENERICMODCONFIGMENU_MOD=${ENABLE_GENERICMODCONFIGMENU_MOD-true}
      - ENABLE_IMMERSIVEFARMREMASTERED_MOD=${ENABLE_IMMERSIVEFARMREMASTERED_MOD-true}
      - ENABLE_JSONASSETS_MOD=${ENABLE_JSONASSETS_MOD-true}
      - ENABLE_SAAT_MOD=${ENABLE_SAAT_MOD-true}
      - ENABLE_SHOPTILEFRAMEWORK_MOD=${ENABLE_SHOPTILEFRAMEWORK_MOD-true}
      - ENABLE_SPACECORE_MOD=${ENABLE_SPACECORE_MOD-true}
      - ENABLE_STARDEWVALLEYEXPANDED_MOD=${ENABLE_STARDEWVALLEYEXPANDED_MOD-true}
      - ENABLE_DEDICATEDSERVER_MOD=${ENABLE_DEDICATEDSERVER_MOD-true}
      - ENABLE_CABINSTACKER_MOD=${ENABLE_CABINSTACKER_MOD-true}
      - ENABLE_BETTERRANCHING_MOD=${ENABLE_BETTERRANCHING_MOD-true}
      - ENABLE_ADVENTURERSGUILDEXPANDED_MOD=${ENABLE_ADVENTURERSGUILDEXPANDED_MOD-true}
      - ENABLE_ERRORHANDLER_MOD=${ENABLE_ERRORHANDLER_MOD-true}
      - ENABLE_MAPEDIT_MOD=${ENABLE_MAPEDIT_MOD-true}
      - ENABLE_SAATADVENTURERSGUILDEXPANDED_MOD=${ENABLE_SAATADVENTURERSGUILDEXPANDED_MOD-true}
      - ENABLE_NPCMAPLOCATIONS_MOD=${ENABLE_NPCMAPLOCATIONS_MOD-true}
      - ENABLE_ATERRARIUM_MOD=${ENABLE_ATERRARIUM_MOD-true}
      - ENABLE_AEROCORE_MOD=${ENABLE_AEROCORE_MOD-true}
      - ENABLE_ALWAYSRAININGINTHEVALLEY_MOD=${ENABLE_ALWAYSRAININGINTHEVALLEY_MOD-true}
      - ENABLE_ANIMALHUSBANDRYMOD_MOD=${ENABLE_ANIMALHUSBANDRYMOD_MOD-true}
      - ENABLE_ANTISOCIALNPCS_MOD=${ENABLE_ANTISOCIALNPCS_MOD-true}
      - ENABLE_ATRACORE_MOD=${ENABLE_ATRACORE_MOD-true}
      - ENABLE_AUTOMATICGATES_MOD=${ENABLE_AUTOMATICGATES_MOD-true}
      - ENABLE_BCTERRARIUM_MOD=${ENABLE_BCTERRARIUM_MOD-true}
      - ENABLE_BLDESERT_MOD=${ENABLE_BLDESERT_MOD-true}
      - ENABLE_BLEASTSCARPEN_MOD=${ENABLE_BLEASTSCARPEN_MOD-true}
      - ENABLE_BEATRICENPC_MOD=${ENABLE_BEATRICENPC_MOD-true}
      - ENABLE_BETTERCHESTS_MOD=${ENABLE_BETTERCHESTS_MOD-true}
      - ENABLE_BETTERWORKBENCHES_MOD=${ENABLE_BETTERWORKBENCHES_MOD-true}
      - ENABLE_BIGGERCRAFTABLES_MOD=${ENABLE_BIGGERCRAFTABLES_MOD-true}
      - ENABLE_BUSLOCATIONS_MOD=${ENABLE_BUSLOCATIONS_MOD-true}
      - ENABLE_CPBALANCEDVALLEY_MOD=${ENABLE_CPBALANCEDVALLEY_MOD-true}
      - ENABLE_CPCANONFRIENDLYDIALOGUEEXPANSION_MOD=${ENABLE_CPCANONFRIENDLYDIALOGUEEXPANSION_MOD-true}
      - ENABLE_CPDAISYNIKOSTILESHEETS_MOD=${ENABLE_CPDAISYNIKOSTILESHEETS_MOD-true}
      - ENABLE_CPFELLOWCLOWNSPATCHESANDTILESHEETS_MOD=${ENABLE_CPFELLOWCLOWNSPATCHESANDTILESHEETS_MOD-true}
      - ENABLE_CPJASPERNPC_MOD=${ENABLE_CPJASPERNPC_MOD-true}
      - ENABLE_CPKROBUSDIALOGUEMODPACKSVE_MOD=${ENABLE_CPKROBUSDIALOGUEMODPACKSVE_MOD-true}
      - ENABLE_CPLUMISTERIATILESHEETSINDOOR_MOD=${ENABLE_CPLUMISTERIATILESHEETSINDOOR_MOD-true}
      - ENABLE_CPLUMISTERIATILESHEETSOUTDOOR_MOD=${ENABLE_CPLUMISTERIATILESHEETSOUTDOOR_MOD-true}
      - ENABLE_CPMIIHAUSMOREHALEYHEARTEVENTS_MOD=${ENABLE_CPMIIHAUSMOREHALEYHEARTEVENTS_MOD-true}
      - ENABLE_CPMOREQUEST_MOD=${ENABLE_CPMOREQUEST_MOD-true}
      - ENABLE_CPRANCHEXPANSION_MOD=${ENABLE_CPRANCHEXPANSION_MOD-true}
      - ENABLE_CPTRAVELINGDREAMER_MOD=${ENABLE_CPTRAVELINGDREAMER_MOD-true}
      - ENABLE_CPWIDEWALLPAPERPACK_MOD=${ENABLE_CPWIDEWALLPAPERPACK_MOD-true}
      - ENABLE_CPYAGISANCUSTOMNPCSFORNPCMAPLOCATIONS_MOD=${ENABLE_CPYAGISANCUSTOMNPCSFORNPCMAPLOCATIONS_MOD-true}
      - ENABLE_CIRCLEOFTHORNS_MOD=${ENABLE_CIRCLEOFTHORNS_MOD-true}
      - ENABLE_CUSTOMCHESTTYPES_MOD=${ENABLE_CUSTOMCHESTTYPES_MOD-true}
      - ENABLE_CUSTOMCOMPANIONS_MOD=${ENABLE_CUSTOMCOMPANIONS_MOD-true}
      - ENABLE_CUSTOMFIXEDDIALOGUE_MOD=${ENABLE_CUSTOMFIXEDDIALOGUE_MOD-true}
      - ENABLE_CUSTOMGIFTDIALOGUE_MOD=${ENABLE_CUSTOMGIFTDIALOGUE_MOD-true}
      - ENABLE_CUSTOMMUSIC_MOD=${ENABLE_CUSTOMMUSIC_MOD-true}
      - ENABLE_CUSTOMNPCFIXES_MOD=${ENABLE_CUSTOMNPCFIXES_MOD-true}
      - ENABLE_DEEPWOODSMOD_MOD=${ENABLE_DEEPWOODSMOD_MOD-true}
      - ENABLE_DESTROYABLEBUSHES_MOD=${ENABLE_DESTROYABLEBUSHES_MOD-true}
      - ENABLE_EASTSCARP_MOD=${ENABLE_EASTSCARP_MOD-true}
      - ENABLE_ESCASMODDINGPLUGINS_MOD=${ENABLE_ESCASMODDINGPLUGINS_MOD-true}
      - ENABLE_EXPANDEDSTORAGE_MOD=${ENABLE_EXPANDEDSTORAGE_MOD-true}
      - ENABLE_FTMBETTERQUARRYREDUX_MOD=${ENABLE_FTMBETTERQUARRYREDUX_MOD-true}
      - ENABLE_FIEVELGOESEASTSCARP_MOD=${ENABLE_FIEVELGOESEASTSCARP_MOD-true}
      - ENABLE_GIFTTASTEHELPER_MOD=${ENABLE_GIFTTASTEHELPER_MOD-true}
      - ENABLE_IMMERSIVEFESTIVALDIALOGUE_MOD=${ENABLE_IMMERSIVEFESTIVALDIALOGUE_MOD-true}
      - ENABLE_IMMERSIVESALOON_MOD=${ENABLE_IMMERSIVESALOON_MOD-true}
      - ENABLE_KROBUSDIALOGUEEXPANSIONMODPACK_MOD=${ENABLE_KROBUSDIALOGUEEXPANSIONMODPACK_MOD-true}
      - ENABLE_LOVEOFCOOKING_MOD=${ENABLE_LOVEOFCOOKING_MOD-true}
      - ENABLE_MFMMOREQUEST_MOD=${ENABLE_MFMMOREQUEST_MOD-true}
      - ENABLE_MNFMORENEWFISH_MOD=${ENABLE_MNFMORENEWFISH_MOD-true}
      - ENABLE_MAILFRAMEWORKMOD_MOD=${ENABLE_MAILFRAMEWORKMOD_MOD-true}
      - ENABLE_MAPPINGEXTENSIONSANDEXTRAPROPERTIES_MOD=${ENABLE_MAPPINGEXTENSIONSANDEXTRAPROPERTIES_MOD-true}
      - ENABLE_MOREKROBUS_MOD=${ENABLE_MOREKROBUS_MOD-true}
      - ENABLE_MOREGRASS_MOD=${ENABLE_MOREGRASS_MOD-true}
      - ENABLE_MOVEIT_MOD=${ENABLE_MOVEIT_MOD-true}
      - ENABLE_MOVEABLEMAILBOX_MOD=${ENABLE_MOVEABLEMAILBOX_MOD-true}
      - ENABLE_MOVEABLEPETBOWL_MOD=${ENABLE_MOVEABLEPETBOWL_MOD-true}
      - ENABLE_NPCJULIETJESSIE_MOD=${ENABLE_NPCJULIETJESSIE_MOD-true}
      - ENABLE_NPCLAVRIL_MOD=${ENABLE_NPCLAVRIL_MOD-true}
      - ENABLE_NPCLURKINGINTHEDARK_MOD=${ENABLE_NPCLURKINGINTHEDARK_MOD-true}
      - ENABLE_NPCRODNEYOBRIEN_MOD=${ENABLE_NPCRODNEYOBRIEN_MOD-true}
      - ENABLE_NPCTRISTAN_MOD=${ENABLE_NPCTRISTAN_MOD-true}
      - ENABLE_NEVERENDINGADVENTURE_MOD=${ENABLE_NEVERENDINGADVENTURE_MOD-true}
      - ENABLE_OUTDOORBUTTERFLYHUTCH_MOD=${ENABLE_OUTDOORBUTTERFLYHUTCH_MOD-true}
      - ENABLE_PLACEBOOKCASESOUTSIDE_MOD=${ENABLE_PLACEBOOKCASESOUTSIDE_MOD-true}
      - ENABLE_PLACECOUCHESANDARMCHAIRSOUTSIDE_MOD=${ENABLE_PLACECOUCHESANDARMCHAIRSOUTSIDE_MOD-true}
      - ENABLE_PLACEDRESSERSFIREPLACESTVSOUTSIDE_MOD=${ENABLE_PLACEDRESSERSFIREPLACESTVSOUTSIDE_MOD-true}
      - ENABLE_PLACEFISHTANKSOUTSIDE_MOD=${ENABLE_PLACEFISHTANKSOUTSIDE_MOD-true}
      - ENABLE_PLACELAMPSOUTSIDE_MOD=${ENABLE_PLACELAMPSOUTSIDE_MOD-true}
      - ENABLE_PLACERUGSOUTSIDE_MOD=${ENABLE_PLACERUGSOUTSIDE_MOD-true}
      - ENABLE_PRODUCERFRAMEWORKMOD_MOD=${ENABLE_PRODUCERFRAMEWORKMOD_MOD-true}
      - ENABLE_QUESTFRAMEWORK_MOD=${ENABLE_QUESTFRAMEWORK_MOD-true}
      - ENABLE_RESPONSECORE_MOD=${ENABLE_RESPONSECORE_MOD-true}
      - ENABLE_SAATESSPIRITSEVE_MOD=${ENABLE_SAATESSPIRITSEVE_MOD-true}
      - ENABLE_SPECIALORDERSEXTENDED_MOD=${ENABLE_SPECIALORDERSEXTENDED_MOD-true}
      - ENABLE_STARDEWAQUARIUM_MOD=${ENABLE_STARDEWAQUARIUM_MOD-true}
      - ENABLE_TMXLOADER_MOD=${ENABLE_TMXLOADER_MOD-true}
      - ENABLE_THELASTSMOLUANU_MOD=${ENABLE_THELASTSMOLUANU_MOD-true}
      - ENABLE_TRAINSTATION_MOD=${ENABLE_TRAINSTATION_MOD-true}
      - ENABLE_WALKTOTHEDESERTREDUXALPHA_MOD=${ENABLE_WALKTOTHEDESERTREDUXALPHA_MOD-true}
      - ENABLE_WALLTELEVISION_MOD=${ENABLE_WALLTELEVISION_MOD-true}
      - ENABLE_XSSSTORAGEVARIETY_MOD=${ENABLE_XSSSTORAGEVARIETY_MOD-true}
      - ENABLE_CPMRGINGER_MOD=${ENABLE_CPMRGINGER_MOD-true}
      - ENABLE_DOWNTOWNZUZUMAIN_MOD=${ENABLE_DOWNTOWNZUZUMAIN_MOD-true}
      - ENABLE_SEASONALCUTECHARACTERJASPER_MOD=${ENABLE_CPSEASONALCUTECHARACTERJASPER_MOD-true}
      - ENABLE_SEASONALCUTECHARACTERSEASTSCARP_MOD=${ENABLE_CPSEASONALCUTECHARACTERSEASTSCARP_MOD-true}
      - ENABLE_SEASONALCUTECHARACTERSJULIETANDJESSIE_MOD=${ENABLE_CPSEASONALCUTECHARACTERSJULIETANDJESSIE_MOD-true}
      - ENABLE_SEASONALCUTECHARACTERSSVE_MOD=${ENABLE_CPSEASONALCUTECHARACTERSSVE_MOD-true}
      - ENABLE_SEASONALCUTECHARACTERSSMOLUANU_MOD=${ENABLE_CPSEASONALCUTECHARACTERSSMOLUANU_MOD-true}
      - ENABLE_SEASONALCUTECHARACTERS_MOD=${ENABLE_CPSEASONALCUTECHARACTERS_MOD-true}
      - ENABLE_SEASONALCUTECHARACTERJASPER_MOD=${ENABLE_SEASONALCUTECHARACTERJASPER_MOD-true}
      - ENABLE_CPMOREHAIR_MOD=${ENABLE_CPMOREHAIR_MOD-true}
      - ENABLE_FASHIONSENSE_MOD=${ENABLE_FASHIONSENSE_MOD=true}
